name: run runner.py

on:
  workflow_dispatch:
  schedule:
    - cron: '45 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r script/requirements.txt

      - name: execute py script # run main.py
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
          FROM: ${{secrets.FROM}}
          APP_PASSWORD: ${{secrets.APP_PASSWORD}}
          account_id: ${{secrets.account_id}}
          auth_token: ${{secrets.auth_token}}
          PHONENUMBER: ${{secrets.PHONENUMBER}}
        run: python script/runner.py